/********************************************************************
* ./include/Dictionary_DmpEvtBgoPID.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./include/Dictionary_DmpEvtBgoPID.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary_DmpEvtBgoPID();
extern void G__cpp_setup_inheritanceDictionary_DmpEvtBgoPID();
extern void G__cpp_setup_typetableDictionary_DmpEvtBgoPID();
extern void G__cpp_setup_memvarDictionary_DmpEvtBgoPID();
extern void G__cpp_setup_globalDictionary_DmpEvtBgoPID();
extern void G__cpp_setup_memfuncDictionary_DmpEvtBgoPID();
extern void G__cpp_setup_funcDictionary_DmpEvtBgoPID();
extern void G__set_cpp_environmentDictionary_DmpEvtBgoPID();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmpEvtBgoPID.h"
#include "DmpEvtBgoPID.h~"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_TClass;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_TBuffer;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_TMemberInspector;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_TObject;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDLN_DmpEvtBgoPID;

/* STUB derived class for protected member access */
